# Game options/settings
TITLE = "My Shmup!"
WIDTH = 576
HEIGHT = 720
FPS = 60
FONT_NAME = 'arial'
HS_FILE = 'highscore.txt'

BAR_LENGTH = 100
BAR_HEIGHT = 20


# define colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)

BG_COLOUR = BLACK

# player attributes
PLAYER_START_Y_OFFSET = 10
PLAYER_SPEED = 8
PLAYER_SHOOT_DELAY = 250
POWERUP_TIME = 5000
PLAYER_START_POWER = 1
PLAYER_MAX_SHIELD = 100
PLAYER_START_LIVES = 3
PLAYER_RESPAWN_TIME = 1000

# star attributes
STAR_MAX_SPEED = 2
STAR_MAX_RADIUS = 2
NUMBER_OF_STARS = 120

# Meteroid attributes
METEOROID_MIN_SPEED_X = -3
METEOROID_MAX_SPEED_X = 3
METEOROID_MIN_SPEED_Y = 1
METEOROID_MAX_SPEED_Y = 8
METEOROID_MIN_ROTATE_SPEED = -8
METEOROID_MAX_ROTATE_SPEED = 8
NUMBER_OF_METEOROIDS = 10

# Explosion attributes
EXPLOSION_FRAME_RATE = 35

# UI attributes
PLAYER_LIVES_ICON_SPACING = 30

# Powerup attributes
POWERUP_SPEED = 4